#!/usr/bin/env bash
shopt -s globstar
export TZ=Etc/UTC

MOUNT_DIRS="${MEDIA_DIRS:-/mnt:/media}"
WORKFLOW_DIR="${WORKFLOW_DIR:-$HOME/Pictures/Workflow}"
CONVERT_OPTIONS=(-auto-orient -resize 1024x1024 -quality 85)
CPUS="$(grep -c ^processor /proc/cpuinfo)"
THREADS="$(echo "$CPUS - 1" | bc)"

# Print a YYYY-MM-DD datestamp for a file in $1, using metadata if available,
# or the modification timstamp if not.
#
datestamp() {
  local file="$1"
  local datestamp="$(metadata_datestamp "$file")"

  if [ "$datestamp" = "" ]; then
    fs_datestamp "$file"
  else
    echo "$datestamp"
  fi
}

# Print the YYYY-MM-DD datestamp of the file in $1 from its metadata, or "" if
# not available.
#
metadata_datestamp() {
  exiv2 "$1" 2>/dev/null \
    | grep 'Image timestamp' \
    | awk '{print $4}' \
    | sed 's/:/-/g'
}

# Print the YYYY-MM-DD modification time of the file in $1.
#
fs_datestamp() {
  stat --dereference --format=%y "$1" | awk '{print $1}'
}

# Import a single file $1 into a directory in $WORKFLOW_DIR/original based on
# its date (creating the directory if necessary).
#
import_one() {
  local original="$1"
  local dest_dir="$WORKFLOW_DIR/original/$(datestamp "$original")"
  local name="$(basename "$original")"
  mkdir -p "$dest_dir"
  if ! [ -e "$dest_dir/$name" ]; then
    echo "Import $original => $dest_dir/$name"
    cp "$original" "$dest_dir/$name.tmp"
    mv "$dest_dir/$name.tmp" "$dest_dir/$name"
  fi
}

# Import all source images and videos found in $MOUNT_DIRS.
#
import_originals() {
  IFS=:
  for mount_dir in $MOUNT_DIRS; do
    if [ -d "$mount_dir" ]; then
      for original in $mount_dir/**/DCIM/**/*.{NEF,JPG,MOV}; do
        unset IFS
        if [ -f "$original" ]; then
          import_one "$original"
        fi
      done
    fi
  done
}

# Generate the preview image for the file $1. Assumes that $1 contains the full
# path to the original, incluing the /original/ directory component.
#
generate_preview() {
  local input="$1"

  if ! [ -f "$1" ]; then
    return
  fi

  local extension="$(echo "$input" | grep -Eio '\.[^\.]+$')"
  local outdir="$(readlink -f "$(dirname "$input")" | sed 's/original/previews/')"
  local output="$outdir/$(basename --suffix="$extension" "$input").jpg"

  if [ -e "$output" ]; then
    return
  fi

  mkdir -p "$outdir"
  echo "Preview $input => $output"

  temp_output="${output}.tmp.jpg"

  case "$extension" in
    .NEF)
      generate_raw_preview "$input" "$temp_output"
      ;;
    .JPG)
      generate_image_preview "$input" "$temp_output"
      ;;
    .MOV)
      generate_video_preview "$input" "$temp_output"
      ;;
    *)
      echo "Can't generate preview for $extension"
      return
      ;;
  esac

  mv "$temp_output" "$output"
}

# Generate a preview image for $1 as $2 using ufraw.
#
generate_raw_preview() {
  local input="$1"
  local output="$2"

  ufraw-batch --overwrite --output=- "$input" 2>/dev/null \
    | convert - "${CONVERT_OPTIONS[@]}" "$output"
}

# Generate a preview image for $1 as $2 using ImageMagick.
#
generate_image_preview() {
  local input="$1"
  local output="$2"
  
  convert "$input" "${CONVERT_OPTIONS[@]}" "$output"
}

# Generate a preview image for $1 as $2. Uses ffmpeg to extract the first frame
# and ImageMagick to add a "Video" caption to the preview.
#
generate_video_preview() {
  local input="$1"
  local output="$2"

  ffmpeg -i "$input" -vcodec ppm -vframes 1 -an -f rawvideo -y - 2>/dev/null \
    | convert - "${CONVERT_OPTIONS[@]}" \
              -fill black -undercolor white -gravity South -annotate +0+5 \
              " Video " "$output"
}

# Generate previews for all images in $WORKFLOW_DIR/originals and put them
# under corresponding dated directories in $WORKFLOW_DIR/previews. Existing
# previews are not replaced.
#
generate_previews() {
  parallel -j "$THREADS" "$0" preview-single-file -- "$WORKFLOW_DIR"/original/**/*
}

# Handle command-line and dispatch accordingly.
#
case "$1" in
  import|i)
    import_originals
    ;;
  preview|p)
    generate_previews
    ;;
  preview-single-file)
    # This is used internally in generate_previews to facilitate parallel
    # processing using GNU parallel.
    generate_preview "$2"
    ;;
  "")
    import_originals
    generate_previews
    ;;
  *)
    echo "Unknown directive $1"
    ;;
esac
