#!/usr/bin/env bash

CONVERT_OPTIONS="-auto-orient -resize 1024x1024 -quality 85"

generate_preview() {
  local input="$1"
  local extension="$(echo "$input" | grep -Eio '\.[^\.]+$')"
  local outdir="$(readlink -f "$(dirname "$input")" | sed 's/original/previews/')"
  local output="$outdir/$(basename --suffix="$extension" "$input").jpg"

  if [ -e "$output" ]; then
    return
  fi

  mkdir -p "$outdir"
  echo "$input -> $output"

  temp_output="${output}.tmp.jpg"

  case "$extension" in
    .NEF)
      generate_nef_preview "$input" "$temp_output"
      ;;
    .JPG)
      generate_jpg_preview "$input" "$temp_output"
      ;;
    *)
      echo "Can't generate preview for $extension"
      return
      ;;
  esac

  mv "$temp_output" "$output"
}

generate_nef_preview() {
  local input="$1"
  local output="$2"

  ufraw-batch --overwrite --output=- "$input" 2>/dev/null \
    | convert - $CONVERT_OPTIONS "$output"
}

generate_jpg_preview() {
  local input="$1"
  local output="$2"
  
  convert "$input" $CONVERT_OPTIONS "$output"
}

for input in "$@"; do
  generate_preview $input
done
