#!/usr/bin/env bash

for input in "$@"; do
  outfile="$(basename --suffix=.NEF "$input").jpg"
  outdir="$(
    readlink -f "$(dirname "$input")" | sed 's/original/previews/'
  )"
  mkdir -p "$outdir"
  output="$outdir/$outfile"
  if ! [ -e "$output" ]; then
    echo "$input -> $output"
    nice ufraw-batch --overwrite --output=- "$input" 2>/dev/null \
      | convert -resize 1024x1024 - "${output}.tmp.jpg"
    mv "${output}.tmp.jpg" "$output"
  fi
done

