#!/usr/bin/env bash
shopt -s globstar

export TZ=Etc/UTC
MOUNT_DIRS="${MEDIA_DIRS:-/mnt:/media}"
WORKFLOW_DIR="${WORKFLOW_DIR:-$HOME/Pictures/Workflow}"

datestamp() {
  local file="$1"
  local datestamp="$(metadata_datestamp "$file")"

  if [ "$datestamp" = "" ]; then
    fs_datestamp "$file"
  else
    echo "$datestamp"
  fi
}

metadata_datestamp() {
  exiv2 "$1" 2>/dev/null \
    | grep 'Image timestamp' \
    | awk '{print $4}' \
    | sed 's/:/-/g'
}

fs_datestamp() {
  stat --dereference --format=%y "$1" | awk '{print $1}'
}

import_one() {
  local original="$1"
  local dest_dir="$WORKFLOW_DIR/original/$(datestamp "$original")"
  local name="$(basename "$original")"
  mkdir -p "$dest_dir"
  if ! [ -e "$dest_dir/$name" ]; then
    echo "$original => $dest_dir/$name"
    cp "$original" "$dest_dir/$name.tmp"
    mv "$dest_dir/$name.tmp" "$dest_dir/$name"
  fi
}

import_originals() {
  local mount_dir="$1"
  IFS=:
  for original in $mount_dir/**/DCIM/**/*.{NEF,JPG,MOV}; do
    unset IFS
    if [ -f "$original" ]; then
      import_one "$original"
    fi
  done
}

IFS=:
for mount_dir in $MOUNT_DIRS; do
  unset IFS
  if [ -d "$mount_dir" ]; then
    import_originals "$mount_dir"
  fi
done
