#!/usr/bin/env bash

export TZ=Etc/UTC
MOUNT_DIRS="/mnt /media"
WORKFLOW_DIR="$HOME/Pictures/Workflow"

datestamp() {
  local file="$1"
  local datestamp="$(metadata_datestamp "$file")"

  if [ "$datestamp" = "" ]; then
    fs_datestamp "$file"
  else
    echo "$datestamp"
  fi
}

metadata_datestamp() {
  exiv2 "$1" 2>/dev/null \
    | grep 'Image timestamp' \
    | awk '{print $4}' \
    | sed 's/:/-/g'
}

fs_datestamp() {
  stat --dereference --format=%y "$1" | awk '{print $1}'
}

import_originals() {
  for mount_dir in $MOUNT_DIRS; do
    if [ -d "$mount_dir" ]; then
      pushd "$mount_dir" >/dev/null
      for original in */**/DCIM/*/*.{NEF,JPG,MOV}; do
        if [ -f "$original" ]; then
          local dest_dir="$WORKFLOW_DIR/original/$(datestamp "$original")"
          local name="$(basename "$original")"
          mkdir -p "$dest_dir"
          if ! [ -e "$dest_dir/$name" ]; then
            echo "$original => $dest_dir/$name"
            cp "$original" "$dest_dir/$name.tmp"
            mv "$dest_dir/$name.tmp" "$dest_dir/$name"
          fi
        fi
      done
      popd >/dev/null
    fi
  done
}

import_originals
