#!/usr/bin/env bash

WORKFLOW_DIR="$HOME/Pictures/Workflow"

CPUS="$(grep ^processor /proc/cpuinfo | wc -l)"
THREADS="$(echo "$CPUS - 1" | bc)"
PREVIEWER="$(dirname "$0")/wf-generate-preview"

parallel -j "$THREADS" "$PREVIEWER" -- $WORKFLOW_DIR/original/**/*
